I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 190, in script
    python:
  File "renpy/common/00start.rpy", line 191, in <module>
    renpy.execute_default_statement(True)
  File "game/scripts/script.rpy", line 10, in set_default
    default arma1_item = Consumable("arma1", 50, 100, 0, "pistola")
  File "game/scripts/script.rpy", line 10, in <module>
    default arma1_item = Consumable("arma1", 50, 100, 0, "pistola")
TypeError: __init__() takes exactly 5 arguments (6 given)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 190, in script
    python:
  File "renpy/ast.py", line 923, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2235, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00start.rpy", line 191, in <module>
    renpy.execute_default_statement(True)
  File "renpy/exports.py", line 3749, in execute_default_statement
    i.set_default(start)
  File "game/scripts/script.rpy", line 10, in set_default
    default arma1_item = Consumable("arma1", 50, 100, 0, "pistola")
  File "renpy/python.py", line 2259, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/scripts/script.rpy", line 10, in <module>
    default arma1_item = Consumable("arma1", 50, 100, 0, "pistola")
TypeError: __init__() takes exactly 5 arguments (6 given)

Windows-10-10.0.19041
Ren'Py 7.4.8.1895
ApenasTeste 1.0
Mon Oct 25 08:27:06 2021
